repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        description: This hook removes trailing whitespace from files
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        name: Fix end of files
        description: This hook ensures files end with a newline
      - id: check-yaml
        name: Check YAML syntax
        description: This hook checks YAML files for valid syntax
      - id: check-toml
        name: Check TOML syntax
        description: This hook checks TOML files for valid syntax
      - id: check-added-large-files
        name: Check for large files
        description: Prevents adding large files to git
        args: [--maxkb=500]
