[build-system]
requires = ["setuptools>=68.2.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "indaleko"
version = "0.1.1"
description = "Indaleko is a Python package for implementing a Unified Personal Index system."
authors = [{name = "Tony Mason", email = "fsgeek@gatech.edu"}]
dependencies = [
    "apischema==0.18.1",
    "discord.py==2.3.2",
    "docker==7.1.0",
    "dropbox==12.0.2",
    "Faker==29.0.0",
    "Flask==3.1.0",
    "geopy==2.4.1",
    "gitpython==3.1.44",
    "google_api_python_client==2.154.0",
    "google_auth_oauthlib==1.2.1",
    "icecream==2.1.3",
    "jsonlines==4.0.0",
    "jsonschema==4.23.0",
    "keyring==24.2.0",
    "msal==1.24.1",
    "msgpack_python==0.5.6",
    "openai==1.47.0",
    "psutil==5.9.7",
    "pydantic==2.9.2",
    "pyicloud==1.0.0",
    "pyngrok==7.2.0",
    "python_arango==7.7.0",
    "Requests==2.32.3",
    "graphql-core==3.2.4",
    "pydantic-core==2.23.4",
    "pytile==2023.12.0",
    "winsdk==1.0.0b10 ; platform_system == 'Windows'",
]
requires-python = ">=3.12"

[project.optional-dependencies]
test = ["pytest>=6.0"]
dev = ["black", "flake8"]
windows = ['winsdk==1.0.0b10']

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.pylint]
init-hook = "import sys; sys.path.insert(0, '${workspaceFolder}')"
