name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev,test]"

      - name: Type-check with mypy
        run: |
          pip install mypy
          mypy .

      - name: Lint with pre-commit
        run: make lint

      - name: Check code formatting
        run: |
          black --check .

      - name: Run tests
        run: make test

      - name: Coverage report
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report